[package]
name = "order_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
rust_decimal = { version = "1.37", features = ["macros", "serde-arbitrary-precision"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
