[project]
name = "txt2video"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "diffusers[torch]>=0.36.0",
    "ftfy>=6.3.1",
    "opencv-python>=4.12.0.88",
    "transformers>=4.57.3",
]
